
INSERT INTO USUARIO(ID, USUARIO, CLAVE, NOMBRE, ESTADO) VALUES(1, 'admin', '$2a$10$7xR4joivDIQYh/XkccDZHO7jtn6fgbRJ5IMe7Xxz7NtchhosJyfQi', 'Administrador', 1);
INSERT INTO ROL(ID, ROL) VALUES(1, 'USUARIOS');
INSERT INTO USUARIO_ROL(USUARIO_ID, ROL_ID) VALUES(1, 1);